### ISSUE TITLE
Demo page doesn’t work

### ISSUE THREAD

**Issue by vovkkk** [hugowetterberg/folding#2]
I assume that clicking headers is supposed to fold/hide content, but nothing happens at all.

Firefox 29 says:

```
TypeError: element.classList is undefined folding.js:23
```

Chromium 36.0.1979.0 (268771) says:

```
Uncaught TypeError: Cannot read property 'add' of undefined folding.js:23
```

IE 11.0.7 doesn’t like line 11 (SCRIPT65535: Недопустимый вызывающий объект, translate like Invalid caller (literally: inappropriate/illegal calling object).

**Comment by hugowetterberg** [comment]
Fixed in 0f5dd50

**Comment by vovkkk** [comment]
Nice, thank you.

BTW, did you notice how awkward it folds the last section (Milestone D or Gameplay.todo)?
Would it make sense and simple enough to add timeout or some sort of animation? so it would be more elegant.

**Comment by hugowetterberg** [comment]
Well, it might depend on the context. Folding is done through classList manipulation, so adding transitions _should_ be pretty easy.
